### ISSUE TITLE
CSL Editor bug with chicago-15/16 page format

### ISSUE THREAD

**Issue by POBrien333** [citation-style-language/styles#5926]
Error message: Citeproc exception: TypeError: me.fun.page_mangler is not a function

![grafik](https://user-images.githubusercontent.com/954979/155540217-6ded88c1-addb-423e-9a1b-a56c3f6081a7.png)

When choosing page-range-format "chicago-15" or 16 I got this error.

**Comment by adam3smith** [comment]
does that style work in Zotero? I'm not sure citeproc-js added support for this.

**Comment by denismaier** [comment]
Let's make sure other people see this. @retorquere

**Comment by retorquere** [comment]
When I try to run the tests using `cslrun -a --reporter spec` I get

```
Rebundling processor

Error: ENOENT: no such file or directory, scandir '/Users/emile/github/citeproc-js/fixtures/std/processor-tests/humans'

Error: ENOENT: no such file or directory, scandir '/Users/emile/github/citeproc-js/fixtures/std/processor-tests/humans'
    at Object.readdirSync (node:fs:1390:3)
    at checkAll (/Users/emile/github/citeproc-js/node_modules/citeproc-test-runner/runtests.js:266:29)
    at fetchTestData (/Users/emile/github/citeproc-js/node_modules/citeproc-test-runner/runtests.js:316:13)
    at bundleValidateTest (/Users/emile/github/citeproc-js/node_modules/citeproc-test-runner/runtests.js:666:9)
    at /Users/emile/github/citeproc-js/node_modules/citeproc-test-runner/runtests.js:871:13
    at Object.<anonymous> (/Users/emile/github/citeproc-js/node_modules/citeproc-test-runner/runtests.js:884:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/emile/github/citeproc-js/fixtures/std/processor-tests/humans'
}
```

I'm trying to get this into a test case before trying to solve it.

**Comment by POBrien333** [comment]
Actually, the style doesn't work.
Zotero throws a validation message, as would be expected, but then when adding the bibliography, it breaks.

![image](https://user-images.githubusercontent.com/954979/155716307-244238a7-1b93-4d7b-8961-0fd9622c1049.png)

Style to test: https://gist.githubusercontent.com/POBrien333/bc9f598282a97e11d061c30457773d99/raw/1925f9de12dead26105c509ab1062009dab06053/international-journal-of-cosmetic-science.csl

**Comment by adam3smith** [comment]
Confirmed & moved to citeproc-js: https://github.com/Juris-M/citeproc-js/issues/206
